#MainSlorp Data File
_dict = {'<:weemst:482613982054842379>': 'WeemstGIF.gif',
         '<a:slorp:532711780099686400>': 'slorp2.gif',
         'slorp time': 'slorp2.gif', 'partytime': 'partytime.gif',
         '<a:partytime:541471401106997259>': 'partytime.gif',
         'party time': 'partytime.gif',
         '<:bensub:530630340805656606>': 'bensnake.png',
         'bensub': 'bensnake.png',
         'ben sub': 'bensnake.png',}
_dict1 = {'<:forsenl:462106459623260161>': '<:pepeL:449016425323954177>',
          '<:pepel:449016425323954177>': '<:pepeL:449016425323954177>',
          '<a:pepelaughing:551856521764536326>': '<:PepeLaugh:482600580771086345> Fuck Pogo',
          '<:pepelaugh:482600580771086345>': '<:PepeLaugh:482600580771086345>'}
_dictDate = {'01/01': 'No Clips Yet!',
             '01/02': 'No Clips Yet!',
             '01/03': 'No Clips Yet!',
             '01/04': 'https://clips.twitch.tv/RudeBlatantCatBabyRage',
             '01/05': '***First Walmart Stream*** https://clips.twitch.tv/HelpfulSpikyEggnogNerfRedBlaster',
             '01/06': 'No Clips Yet!',
             '01/07': 'https://clips.twitch.tv/PricklySwissGoldfishPicoMause',
             '01/08': 'No Clips Yet!',
             '01/09': 'No Clips Yet!',
             '01/10': 'No Clips Yet!',
             '01/11': 'No Clips Yet!',
             '01/12': 'No Clips Yet!',
             '01/13': 'No Clips Yet!',
             '01/14': 'No Clips Yet!',
             '01/15': 'No Clips Yet!',
             '01/16': 'No Clips Yet!',
             '01/17': 'No Clips Yet!',
             '01/18': 'https://clips.twitch.tv/DirtyAbnegateDonkeyDansGame',
             '01/19': 'https://clips.twitch.tv/ImpossibleSparklySalsifyANELE',
             '01/20': 'No Clips Yet!',
             '01/21': 'No Clips Yet!',
             '01/22': 'No Clips Yet!',
             '01/23': 'https://clips.twitch.tv/SpicySmallMouseRlyTho',
             '01/24': 'No Clips Yet!',
             '01/25': 'No Clips Yet!',
             '01/26': 'No Clips Yet!',
             '01/27': 'No Clips Yet!',
             '01/28': 'No Clips Yet!',
             '01/29': 'https://clips.twitch.tv/JazzyCrypticSkirretTBTacoLeft',
             '01/30': 'No Clips Yet!',
             '01/31': 'No Clips Yet!',
             '02/01': 'No Clips Yet!',
             '02/02': 'https://clips.twitch.tv/DifficultHomelyMagpieDoubleRainbow',
             '02/03': 'No Clips Yet!',
             '02/04': 'No Clips Yet!',
             '02/05': 'https://clips.twitch.tv/SuperPreciousDiamondUncleNox',
             '02/06': 'https://clips.twitch.tv/NeighborlyPoliteSlothPJSalt',
             '02/07': 'No Clips Yet!',
             '02/08': 'No Clips Yet!',
             '02/09': 'No Clips Yet!',
             '02/10': 'https://clips.twitch.tv/YawningTenuousSushiCoolStoryBob',
             '02/11': 'No Clips Yet!',
             '02/12': 'No Clips Yet!',
             '02/13': 'No Clips Yet!',
             '02/14': 'No Clips Yet!',
             '02/15': 'No Clips Yet!',
             '02/16': 'No Clips Yet!',
             '02/17': 'No Clips Yet!',
             '02/18': 'No Clips Yet!',
             '02/19': 'No Clips Yet!',
             '02/20': 'https://clips.twitch.tv/InterestingNimbleKoupreyDoritosChip',
             '02/21': 'No Clips Yet!',
             '02/22': 'No Clips Yet!',
             '02/23': 'No Clips Yet!',
             '02/24': 'No Clips Yet!',
             '02/25': 'No Clips Yet!',
             '02/26': 'No Clips Yet!',
             '02/27': 'https://clips.twitch.tv/ThankfulThankfulEggNinjaGrumpy',
             '02/28': 'No Clips Yet!',
             '02/29': 'No Clips Yet!',
             '03/01': 'https://clips.twitch.tv/CovertEnticingPonyFUNgineer',
             '03/02': 'https://clips.twitch.tv/BumblingAntsyPrariedogFreakinStinkin',
             '03/03': 'No Clips Yet!',
             '03/04': 'https://clips.twitch.tv/ResourcefulAmericanSangPMSTwin',
             '03/05': 'No Clips Yet!',
             '03/06': 'No Clips Yet!',
             '03/07': 'No Clips Yet!',
             '03/08': 'No Clips Yet!',
             '03/09': 'No Clips Yet!',
             '03/10': 'No Clips Yet!',
             '03/11': 'No Clips Yet!',
             '03/12': 'No Clips Yet!',
             '03/13': 'No Clips Yet!',
             '03/14': 'https://clips.twitch.tv/PowerfulAssiduousSagePJSalt',
             '03/15': 'No Clips Yet!',
             '03/16': 'https://clips.twitch.tv/ColorfulNeighborlyChamoisFUNgineer',
             '03/17': 'No Clips Yet!',
             '03/18': 'https://clips.twitch.tv/DeliciousPreciousFennelPunchTrees',
             '03/19': 'No Clips Yet!',
             '03/20': 'No Clips Yet!',
             '03/21': 'No Clips Yet!',
             '03/22': 'https://clips.twitch.tv/SuperStrangeNostrilJebaited',
             '03/23': 'https://clips.twitch.tv/BitterShyArmadilloDendiFace https://clips.twitch.tv/FurtiveFastMetalJebaited',
             '03/24': 'No Clips Yet!',
             '03/25': 'No Clips Yet!',
             '03/26': 'https://clips.twitch.tv/SpinelessBusyPresidentResidentSleeper',
             '03/27': 'https://clips.twitch.tv/TangentialUnusualOctopusBIRB',
             '03/28': 'No Clips Yet!',
             '03/29': 'No Clips Yet!',
             '03/30': 'No Clips Yet!',
             '03/31': 'https://clips.twitch.tv/TawdryDeterminedClintHoneyBadger',
             '04/01': 'No Clips Yet!',
             '04/02': 'No Clips Yet!',
             '04/03': 'No Clips Yet!',
             '04/04': 'No Clips Yet!',
             '04/05': 'https://clips.twitch.tv/MoralElatedMangoCeilingCat',
             '04/06': 'No Clips Yet!',
             '04/07': 'No Clips Yet!',
             '04/08': 'No Clips Yet!',
             '04/09': 'No Clips Yet!',
             '04/10': 'No Clips Yet!',
             '04/11': 'No Clips Yet!',
             '04/12': 'No Clips Yet!',
             '04/13': 'https://clips.twitch.tv/PerfectLazyNeanderthalVoteYea',
             '04/14': 'No Clips Yet!',
             '04/15': 'https://clips.twitch.tv/ImpossibleVainLaptopCoolStoryBob',
             '04/16': 'No Clips Yet!',
             '04/17': 'https://clips.twitch.tv/PhilanthropicPhilanthropicPelicanSwiftRage',
             '04/17': 'No Clips Yet!',
             '04/18': 'No Clips Yet!',
             '04/19': 'No Clips Yet!',
             '04/20': 'No Clips Yet!',
             '04/21': 'No Clips Yet!',
             '04/22': 'No Clips Yet!',
             '04/23': 'https://clips.twitch.tv/BovineGorgeousBasenjiStoneLightning',
             '04/24': 'https://clips.twitch.tv/TalentedBenevolentSnoodKeepo',
             '04/25': 'No Clips Yet!',
             '04/26': 'No Clips Yet!',
             '04/27': 'No Clips Yet!',
             '04/28': 'https://clips.twitch.tv/BadDiligentWaspPeteZaroll https://clips.twitch.tv/AbnegateLittleGarageDxCat',
             '04/29': 'https://clips.twitch.tv/CreativeRoundLEDNinjaGrumpy',
             '04/30': 'No Clips Yet!',
             '05/01': 'https://clips.twitch.tv/AlluringSuspiciousBasenjiHassanChop',
             '05/02': 'No Clips Yet!',
             '05/03': 'https://clips.twitch.tv/TubularSnappyMosquitoSSSsss',
             '05/04': 'No Clips Yet!',
             '05/05': 'No Clips Yet!',
             '05/06': 'No Clips Yet!',
             '05/07': 'No Clips Yet!',
             '05/08': 'No Clips Yet!',
             '05/09': 'No Clips Yet!',
             '05/10': 'https://clips.twitch.tv/AnimatedColorfulSandpiperSuperVinlin',
             '05/11': 'https://clips.twitch.tv/FrailZanyFungusOMGScoots',
             '05/12': 'No Clips Yet!',
             '05/13': 'No Clips Yet!',
             '05/14': 'No Clips Yet!',
             '05/15': 'No Clips Yet!',
             '05/16': 'No Clips Yet!',
             '05/17': 'No Clips Yet!',
             '05/18': 'https://clips.twitch.tv/OddUgliestWombatSeemsGood',
             '05/19': 'No Clips Yet!',
             '05/20': 'No Clips Yet!',
             '05/21': 'No Clips Yet!',
             '05/22': 'No Clips Yet!',
             '05/23': 'No Clips Yet!',
             '05/24': 'No Clips Yet!',
             '05/25': 'No Clips Yet!',
             '05/26': 'https://clips.twitch.tv/WealthyMiniatureWatermelonTwitchRPG',
             '05/27': 'No Clips Yet!',
             '05/28': 'No Clips Yet!',
             '05/29': 'No Clips Yet!',
             '05/30': 'No Clips Yet!',
             '05/31': 'No Clips Yet!',
             '06/01': 'No Clips Yet!',
             '06/02': 'No Clips Yet!',
             '06/03': 'No Clips Yet!',
             '06/04': 'No Clips Yet!',
             '06/05': 'No Clips Yet!',
             '06/06': 'No Clips Yet!',
             '06/07': 'No Clips Yet!',
             '06/08': 'No Clips Yet!',
             '06/09': 'No Clips Yet!',
             '06/10': 'No Clips Yet!',
             '06/11': 'No Clips Yet!',
             '06/12': 'No Clips Yet!',
             '06/13': 'No Clips Yet!',
             '06/14': 'No Clips Yet!',
             '06/15': 'No Clips Yet!',
             '06/16': 'No Clips Yet!',
             '06/17': 'No Clips Yet!',
             '06/18': 'No Clips Yet!',
             '06/19': 'No Clips Yet!',
             '06/20': 'No Clips Yet!',
             '06/21': 'No Clips Yet!',
             '06/22': 'No Clips Yet!',
             '06/23': 'No Clips Yet!',
             '06/24': 'https://clips.twitch.tv/WonderfulGrossBibimbapGOWSkull',
             '06/25': 'No Clips Yet!',
             '06/26': 'No Clips Yet!',
             '06/27': 'No Clips Yet!',
             '06/28': 'No Clips Yet!',
             '06/29': 'No Clips Yet!',
             '06/30': 'No Clips Yet!',
             '07/01': 'No Clips Yet!',
             '07/02': 'No Clips Yet!',
             '07/03': 'No Clips Yet!',
             '07/04': 'No Clips Yet!',
             '07/05': 'No Clips Yet!',
             '07/06': 'No Clips Yet!',
             '07/07': 'No Clips Yet!',
             '07/08': 'No Clips Yet!',
             '07/09': 'No Clips Yet!',
             '07/10': 'No Clips Yet!',
             '07/11': 'No Clips Yet!',
             '07/12': 'No Clips Yet!',
             '07/13': 'No Clips Yet!',
             '07/14': 'No Clips Yet!',
             '07/15': 'No Clips Yet!',
             '07/16': 'No Clips Yet!',
             '07/17': 'No Clips Yet!',
             '07/18': 'No Clips Yet!',
             '07/19': 'No Clips Yet!',
             '07/20': 'No Clips Yet!',
             '07/21': 'No Clips Yet!',
             '07/22': 'No Clips Yet!',
             '07/23': 'No Clips Yet!',
             '07/24': 'No Clips Yet!',
             '07/25': 'No Clips Yet!',
             '07/26': 'No Clips Yet!',
             '07/27': 'No Clips Yet!',
             '07/28': 'No Clips Yet!',
             '07/29': 'No Clips Yet!',
             '07/30': 'No Clips Yet!',
             '07/31': 'No Clips Yet!',
             '08/01': 'No Clips Yet!',
             '08/02': 'No Clips Yet!',
             '08/03': 'No Clips Yet!',
             '08/04': 'No Clips Yet!',
             '08/05': 'No Clips Yet!',
             '08/06': 'No Clips Yet!',
             '08/07': 'No Clips Yet!',
             '08/08': 'No Clips Yet!',
             '08/09': 'No Clips Yet!',
             '08/10': 'No Clips Yet!',
             '08/11': 'No Clips Yet!',
             '08/12': 'No Clips Yet!',
             '08/13': 'No Clips Yet!',
             '08/14': 'No Clips Yet!',
             '08/15': 'No Clips Yet!',
             '08/16': 'No Clips Yet!',
             '08/17': 'No Clips Yet!',
             '08/18': 'No Clips Yet!',
             '08/19': 'No Clips Yet!',
             '08/20': 'No Clips Yet!',
             '08/21': 'No Clips Yet!',
             '08/22': 'No Clips Yet!',
             '08/23': 'No Clips Yet!',
             '08/24': 'No Clips Yet!',
             '08/25': 'No Clips Yet!',
             '08/26': 'No Clips Yet!',
             '08/27': 'No Clips Yet!',
             '08/28': 'No Clips Yet!',
             '08/29': 'No Clips Yet!',
             '08/30': 'No Clips Yet!',
             '08/31': 'No Clips Yet!',
             '09/01': 'No Clips Yet!',
             '09/02': 'No Clips Yet!',
             '09/03': 'No Clips Yet!',
             '09/04': 'No Clips Yet!',
             '09/05': 'No Clips Yet!',
             '09/06': 'No Clips Yet!',
             '09/07': 'No Clips Yet!',
             '09/08': 'No Clips Yet!',
             '09/09': 'No Clips Yet!',
             '09/10': 'No Clips Yet!',
             '09/11': 'No Clips Yet!',
             '09/12': 'No Clips Yet!',
             '09/13': 'No Clips Yet!',
             '09/14': 'No Clips Yet!',
             '09/15': '***Oldest Clip I Have!*** https://clips.twitch.tv/FineAthleticClintmullinsBatChest',
             '09/16': 'No Clips Yet!',
             '09/17': 'No Clips Yet!',
             '09/18': 'No Clips Yet!',
             '09/19': 'No Clips Yet!',
             '09/20': 'No Clips Yet!',
             '09/21': 'No Clips Yet!',
             '09/22': 'No Clips Yet!',
             '09/23': 'No Clips Yet!',
             '09/24': 'No Clips Yet!',
             '09/25': 'No Clips Yet!',
             '09/26': 'No Clips Yet!',
             '09/27': 'No Clips Yet!',
             '09/28': 'No Clips Yet!',
             '09/29': 'No Clips Yet!',
             '09/30': 'No Clips Yet!',
             '10/01': 'No Clips Yet!',
             '10/02': 'No Clips Yet!',
             '10/03': 'No Clips Yet!',
             '10/04': 'No Clips Yet!',
             '10/05': 'https://clips.twitch.tv/MotionlessAbstemiousLampOhMyDog',
             '10/06': 'No Clips Yet!',
             '10/07': 'No Clips Yet!',
             '10/08': 'No Clips Yet!',
             '10/09': 'No Clips Yet!',
             '10/10': 'No Clips Yet!',
             '10/11': 'No Clips Yet!',
             '10/12': 'No Clips Yet!',
             '10/13': 'No Clips Yet!',
             '10/14': 'No Clips Yet!',
             '10/15': 'No Clips Yet!',
             '10/16': 'No Clips Yet!',
             '10/17': 'No Clips Yet!',
             '10/18': 'No Clips Yet!',
             '10/19': 'No Clips Yet!',
             '10/20': 'https://clips.twitch.tv/DullDifferentDragonJKanStyle https://clips.twitch.tv/BoringCheerfulLettucePJSalt',
             '10/21': 'https://clips.twitch.tv/AgilePolishedBasenjiWow',
             '10/22': 'No Clips Yet!',
             '10/23': 'No Clips Yet!',
             '10/24': 'No Clips Yet!',
             '10/25': 'No Clips Yet!',
             '10/26': 'No Clips Yet!',
             '10/27': 'No Clips Yet!',
             '10/28': 'No Clips Yet!',
             '10/29': 'No Clips Yet!',
             '10/30': 'https://clips.twitch.tv/EnjoyableStormyBeefRitzMitz',
             '10/31': 'No Clips Yet!',
             '11/01': 'No Clips Yet!',
             '11/02': 'No Clips Yet!',
             '11/03': 'No Clips Yet!',
             '11/04': 'No Clips Yet!',
             '11/05': 'No Clips Yet!',
             '11/06': 'No Clips Yet!',
             '11/07': 'No Clips Yet!',
             '11/08': 'No Clips Yet!',
             '11/09': 'No Clips Yet!',
             '11/10': 'No Clips Yet!',
             '11/11': 'No Clips Yet!',
             '11/12': 'No Clips Yet!',
             '11/13': 'No Clips Yet!',
             '11/14': 'No Clips Yet!',
             '11/15': 'https://clips.twitch.tv/WittyKitschyMangoRedCoat https://clips.twitch.tv/WittyKitschyMangoRedCoat',
             '11/16': 'No Clips Yet!',
             '11/17': 'https://clips.twitch.tv/RepleteFilthyLaptopMingLee https://clips.twitch.tv/SmilingBoringPassionfruitTooSpicy',
             '11/18': 'No Clips Yet!',
             '11/19': 'No Clips Yet!',
             '11/20': 'No Clips Yet!',
             '11/21': 'No Clips Yet!',
             '11/22': 'No Clips Yet!',
             '11/23': 'No Clips Yet!',
             '11/24': 'No Clips Yet!',
             '11/25': 'No Clips Yet!',
             '11/26': 'https://clips.twitch.tv/BeautifulHardKumquatNinjaGrumpy',
             '11/27': 'https://clips.twitch.tv/ArborealFreezingLeopardDerp',
             '11/28': 'No Clips Yet!',
             '11/29': 'No Clips Yet!',
             '11/30': 'https://clips.twitch.tv/TubularWiseWoodpeckerDoubleRainbow',
             '12/01': 'No Clips Yet!',
             '12/02': 'https://clips.twitch.tv/SparklyRelentlessPlumberPicoMause',
             '12/03': 'No Clips Yet!',
             '12/04': 'No Clips Yet!',
             '12/05': 'No Clips Yet!',
             '12/06': 'No Clips Yet!',
             '12/07': 'No Clips Yet!',
             '12/08': 'https://clips.twitch.tv/ClearLuckyMilkWOOP',
             '12/09': 'No Clips Yet!',
             '12/10': 'https://clips.twitch.tv/DeafObeseCrocodileCoolStoryBro',
             '12/11': 'No Clips Yet!',
             '12/12': 'https://clips.twitch.tv/AwkwardBovineLampWoofer',
             '12/13': 'No Clips Yet!',
             '12/14': 'No Clips Yet!',
             '12/15': 'No Clips Yet!',
             '12/16': 'No Clips Yet!',
             '12/17': 'https://clips.twitch.tv/WiseRacyStrawberryHotPokket',
             '12/18': 'https://clips.twitch.tv/GlamorousTangentialKiwiSwiftRage',
             '12/19': 'No Clips Yet!',
             '12/20': 'No Clips Yet!',
             '12/21': '***First 24 Hour Stream*** https://clips.twitch.tv/LaconicArbitraryCattleSoonerLater https://clips.twitch.tv/ProudUglyGazelleDendiFace',
             '12/22': 'No Clips Yet!',
             '12/23': 'https://clips.twitch.tv/HungryAbstrusePepperoniTF2John',
             '12/24': '***Christmas With Family :)*** https://clips.twitch.tv/ArtisticAntediluvianFennelDogFace https://clips.twitch.tv/ModernCovertRingYouWHY',
             '12/25': 'No Clips Yet!',
             '12/26': 'https://clips.twitch.tv/AgitatedFairGullDoggo',
             '12/27': 'No Clips Yet!',
             '12/28': 'No Clips Yet!',
             '12/29': 'https://clips.twitch.tv/ColorfulTacitMeerkatRuleFive',
             '12/30': 'No Clips Yet!',
             '12/31': 'No Clips Yet!'
             } 
